[package]
name = "ft_token"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
uint = { version = "0.9.1", default-features = false }

[profile.release]
overflow-checks = false
panic = "abort"


